 # database 연동 설정
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    각자 PC에 만들어놓은 Database이름을 써야 합니다.
    #url: jdbc:mysql://localhost:3306/db_bs?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    url: jdbc:mysql://localhost:3306/potatomarket?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8&useSSL=true
#    mysql에 생성한 사용자 계정 정보를 써야 합니다.
    username: root
    password: developerchaewon13!
  thymeleaf:
    cache: false

  # spring data jpa 설정
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
     
    properties:
      hibernate:
        show-sql: true
        format-sql: true
  
    #database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    #open-in-view: false
    #show-sql: true
    #hibernate:
      #ddl-auto: update